# Generated by Django 3.0.5 on 2020-05-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20200513_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
