# Generated by Django 3.0.5 on 2020-05-19 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0002_auto_20200519_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='collected',
            field=models.ManyToManyField(blank=True, related_name='collected_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
